export const intakeSignals = [
  { label: 'Founder interview', detail: 'Strategic goals, market context, operating constraints', volume: '42m' },
  { label: 'Sales transcript set', detail: 'Lead qualification, objection handling, handoff gaps', volume: '18 files' },
  { label: 'CRM export', detail: 'Pipeline stage velocity, lost revenue patterns', volume: '8.4k rows' },
  { label: 'SOP library', detail: 'Delivery, support, onboarding, escalation procedures', volume: '31 docs' },
];

export const orchestrationStages = [
  { stage: 'Normalize', copy: 'Parsing company memory into stable operating primitives.', progress: 100 },
  { stage: 'Map', copy: 'Identifying teams, dependencies, decisions, loops, and leakage.', progress: 100 },
  { stage: 'Architect', copy: 'Designing agents, workflows, memory boundaries, and escalation logic.', progress: 82 },
  { stage: 'Package', copy: 'Preparing repository scaffold, deployment topology, and executive narrative.', progress: 46 },
];

export const agents = [
  { name: 'Revenue Cartographer', domain: 'Sales', objective: 'Qualify intent, preserve context, route next best actions.', access: 'CRM + call memory', kpi: 'Speed-to-lead' },
  { name: 'Client Onboarding Operator', domain: 'Success', objective: 'Convert signed clients into sequenced activation plans.', access: 'SOPs + project plans', kpi: 'Time-to-value' },
  { name: 'Knowledge Steward', domain: 'Memory', objective: 'Maintain trusted operational memory and retrieval hygiene.', access: 'Docs + transcripts', kpi: 'Recall accuracy' },
  { name: 'Executive Synthesis Agent', domain: 'Leadership', objective: 'Surface bottlenecks, risks, and strategic decisions.', access: 'All summarized signals', kpi: 'Decision latency' },
  { name: 'Support Triage Analyst', domain: 'Support', objective: 'Classify issues, propose resolutions, escalate exceptions.', access: 'Tickets + policies', kpi: 'First response' },
];

export const workflows = [
  { title: 'Inbound lead intelligence', trigger: 'New qualified lead', agents: ['Revenue Cartographer', 'Executive Synthesis Agent'], result: 'Context-rich opportunity brief with risk and next action.' },
  { title: 'Client activation sequence', trigger: 'Closed-won deal', agents: ['Client Onboarding Operator', 'Knowledge Steward'], result: 'Autogenerated kickoff plan, asset requests, and timeline.' },
  { title: 'Operational memory refresh', trigger: 'New transcript or SOP', agents: ['Knowledge Steward'], result: 'Versioned memory update with confidence and expiration rules.' },
  { title: 'Leadership operating brief', trigger: 'Weekly cadence', agents: ['Executive Synthesis Agent'], result: 'Five-page executive narrative: blockers, leverage, decisions.' },
];

export const repositoryTree = [
  'client-os/',
  '├─ agents/revenue-cartographer.ts',
  '├─ agents/onboarding-operator.ts',
  '├─ memory/company-context.json',
  '├─ workflows/inbound-lead.yaml',
  '├─ workflows/client-activation.yaml',
  '├─ dashboards/executive-brief.tsx',
  '├─ infra/serverless-functions/',
  '└─ README_DEPLOYMENT.md',
];

export const dashboardMetrics = [
  { label: 'Automation leverage', value: '38%', note: 'Estimated cognitive labor reduction in first 45 days' },
  { label: 'Revenue leakage', value: '$184k', note: 'Recoverable pipeline risk from slow follow-up and handoff loss' },
  { label: 'Memory stability', value: '71%', note: 'SOP coverage weighted by workflow criticality' },
  { label: 'Deployment readiness', value: '86%', note: 'MVP architecture ready for Vercel serverless rollout' },
];
